# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import datetime
import random, string

def gen_sponsorship_codes(apps, schema_editor):
    """
    Add sponsorship codes for the 2016 "slim" campaign
    """
    User                = apps.get_model("user_mgr", "User")
    PromotionalCode     = apps.get_model("user_mgr", "PromotionalCode")

    # Retrieving users with "slim" diet
    users = list(User.objects.filter(diet__key="slim", enabled=True))
    # Generating a sponsorship code for each of them
    codes = []
    while len(codes) != len(users):
        is_unique = False
        while not is_unique:
            code = "".join(random.choice(string.ascii_uppercase) for i in range(9))
            if code not in codes:
                break
        codes.append(code[:3] + "-" + code[3:6] + "-" + code[6:])

    # Associating the sponsorship code in their accounts
    for i, user in enumerate(users):
        user.sponsorship_code = PromotionalCode.objects.create(code=codes[i], name=user.email,
                                   benefit="PREMIUM", can_be_activated_until=datetime.datetime(2016, 7, 1),
                                   benefit_until=datetime.datetime(2016, 7, 1))
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('user_mgr', '0009_the_slim_operation_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sponsorship_code',
            field=models.ForeignKey(related_name='users_who_consumed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_mgr.PromotionalCode'),
        ),
        migrations.RunPython(gen_sponsorship_codes)
    ]
