# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgr', '0010_user_sponsorship_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='promotional_codes',
            field=models.ManyToManyField(related_name='users_who_consumed', to='user_mgr.PromotionalCode'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sponsorship_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_mgr.PromotionalCode'),
        ),
    ]
