# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 14:43
from __future__ import unicode_literals

from django.db import migrations, models

def set_users_nutrient_packs(apps, schema_editor):

    NutrientPack = apps.get_model('nutrient', 'NutrientPack')
    User         = apps.get_model('user_mgr', 'User')

    default_pack = NutrientPack.objects.get(key="default")
    for user in User.objects.all():
        user.nutrient_packs.add(default_pack)



class Migration(migrations.Migration):

    dependencies = [
        ('nutrient', '0005_auto_20180116_1531'),
        ('user_mgr', '0011_auto_20160624_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nutrient_packs',
            field=models.ManyToManyField(to='nutrient.NutrientPack'),
        ),
        migrations.RunPython(set_users_nutrient_packs)
    ]
