# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgr', '0012_user_nutrient_packs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='sent_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pro',
        ),
        migrations.AddField(
            model_name='user',
            name='biodymanager_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
