# Generated by Django 2.0.2 on 2018-02-05 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgr', '0013_auto_20180118_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet_mgr.Diet'),
        ),
    ]
