# Generated by Django 2.0.8 on 2018-08-23 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgr', '0014_auto_20180205_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutologinToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='access_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autologintoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
