# Generated by Django 2.0.8 on 2018-11-21 13:36

from django.db import migrations, models
from django.db.models import F


def define_mail_suggestion(apps, schema_editor):
    User = apps.get_model('user_mgr', 'User')

    User.objects.all().update(mail_suggestion=F('mail_daily'))

class Migration(migrations.Migration):

    dependencies = [
        ('user_mgr', '0015_auto_20180823_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='mail_suggestion',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(define_mail_suggestion)
    ]
