# Generated by Django 2.0.8 on 2019-06-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgr', '0016_baseuser_mail_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='mail_daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='mail_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='mail_suggestion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='nutrient_packs',
            field=models.ManyToManyField(related_name='users', to='nutrient.NutrientPack'),
        ),
    ]
