# Generated by Django 4.2.7 on 2024-01-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrient', '0006_auto_20180119_1436'),
        ('user_mgr', '0017_auto_20190605_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='mail_daily',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='mail_newsletter',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='mail_suggestion',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nutrient_packs',
            field=models.ManyToManyField(to='nutrient.nutrientpack'),
        ),
    ]
