# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_mgr', '0014_auto_20151210_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodseasonality',
            name='food',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='season', to='recipe_mgr.Food'),
        ),
    ]
