# Generated by Django 2.0.2 on 2018-02-05 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_mgr', '0015_auto_20160317_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='default_conversion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_foods', to='recipe_mgr.FoodConversion'),
        ),
        migrations.AlterField(
            model_name='food',
            name='default_cooking_method',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_mgr.CookingMethod'),
        ),
        migrations.AlterField(
            model_name='food',
            name='default_raw_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_mgr.RawState'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipe_mgr.FoodSource'),
        ),
        migrations.AlterField(
            model_name='food',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipe_mgr.Food'),
        ),
        migrations.AlterField(
            model_name='food',
            name='shopping_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopping_mgr.ShoppingCategory'),
        ),
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='recipe_mgr.FoodType'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipe_mgr.FoodSource'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cooking_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipe_mgr.CookingMethod'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='default_conversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='recipe_mgr.FoodConversion'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipe_mgr.Food'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='raw_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipe_mgr.RawState'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location_mgr.Location'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='publisher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipetag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipe_mgr.RecipeTag'),
        ),
        migrations.AlterField(
            model_name='ustensil',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipe_mgr.UstensilCategory'),
        ),
    ]
