# Generated by Django 2.0.8 on 2018-09-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_mgr', '0017_recipe_perceived_as_non_healthy'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
