# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_mgr', '0002_auto_20150609_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forced_base_calories',
            field=models.IntegerField(null=True),
        ),
    ]
