# Number of plannings
population_size: 20

# Number of loops in the algorithm
nb_generations: 5000
max_lost_generations: 20

# Percentage (float) of oriented improvements
# crossover / mutation
oriented_crossover_rate_start: 0
oriented_crossover_rate_end: 1
oriented_mutation_rate_start: 0
oriented_mutation_rate_end: 1

ratio_change_rate: 0.25

crossover_rate: 1
mutation_rate: 1

selection: elitism