# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 13:45
from __future__ import unicode_literals

from django.db import migrations


def disable_slim_diet(apps, schema_editor):
    Diet    = apps.get_model("diet_mgr", "Diet")
    
    balanced = Diet.objects.get(key="slim")
    balanced.enabled = False
    balanced.save()

class Migration(migrations.Migration):

    dependencies = [
        ('diet_mgr', '0009_auto_20151030_1620'),
    ]

    operations = [
        # migrations.RunPython(disable_slim_diet)
    ]
