# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 10:07
from __future__ import unicode_literals

from django.db import migrations


def rename_diets_for_seo(apps, schema_editor):
    Diet    = apps.get_model("diet_mgr", "Diet")

    diet_url_keys = {
        "balanced" : "reequilibrage-alimentaire",
        "slim" : "menus-minceur",
        "gluten_free": "menus-sans-gluten",
        "vegetarian": "menus-vegetariens",
        "vegan": "menus-vegan",
        "easy_digest": "menus-meilleure-digestion-normal-leger",
        "cardiovascular": "menus-pour-le-coeur",
        "diabete": "menus-diabete",
        "hypertension": "menus-hypertension",
        "normolipidic": "menus-cholesterol",
    }

    for diet in Diet.objects.all():
        diet.url_key = diet_url_keys[diet.key]
        if diet.key == "balanced":
            diet.title = "Equilibré"
        diet.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('diet_mgr', '0010_auto_20160624_1545'),
    ]

    operations = [
        # migrations.RunPython(rename_diets_for_seo)
    ]
