# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-09 17:42
from __future__ import unicode_literals

from django.db import migrations


def premium_strikes_back(apps, schema_editor):
    Diet    = apps.get_model("diet_mgr", "Diet")

    for diet in Diet.objects.filter(key__in=["slim", "easy_digest", "hypertension", "normolipidic", "diabete", "cardiovascular"]):
        diet.free_trial_days = 7
        diet.enabled = diet.key != "cardiovascular"
        diet.min_subscription_level = 1
        diet.save()

class Migration(migrations.Migration):

    dependencies = [
        ('diet_mgr', '0012_auto_20160726_1123'),
    ]

    operations = [
        migrations.RunPython(premium_strikes_back)
    ]
