# Generated by Django 2.0.8 on 2019-06-05 14:26

from django.db import migrations, models


def set_diet_ranks(apps, schema_editor):

    Diet = apps.get_model('diet_mgr', 'Diet')

    for i, diet in enumerate(Diet.objects.all()):
        diet.rank = i + 1
        diet.save()


class Migration(migrations.Migration):

    dependencies = [
        ('diet_mgr', '0014_auto_20180105_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(set_diet_ranks)
    ]
