# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 13:36
from __future__ import unicode_literals

from django.db import migrations, models


INDICATOR_PACKS = {
    'stress':
        {'title': 'Pack "Anti-stress, relaxation, anti-fatigue"',
         'description': 'Contrôle optimal de vos apports en magnésium et vitamines B afin de réduire la nervosité',
         'indicators': [
            'magnesium',
            'zinc',
            'calcium',
            'vitamineb1',
            'vitamineb2',
            'vitamineb3',
            'vitamineb6',
            'vitamineb9',
            'vitaminec'
        ]},
    'immune':
        {'title': 'Pack "Système immunitaire"',
         'description': 'Contrôle des nutriments essentiels au bon fonctionnement du système immunitaire',
         'warning': 'La vitamine D joue un rôle important dans le système immunitaire, mais les apports sont difficiles à atteindre dans le cadre alimentaire. De plus, le corps sait en fabriquer lui-même par l\'exposition de la peau aux rayons du soleil. 90% des français sont carencés en vitamine D. Parlez-en à votre médecin, qui pourra vous prescrire une éventuelle supplémentation.',
         'indicators': [
            "vitaminea",
            'vitamineb6',
            "vitaminec",
            "vitaminee",
            'cuivre',
            'zinc'
        ]},
    'bones':
        {'title': 'Pack "Solidité des os et confort des articulations"',
        'description': 'Tous les apports optimaux pour le bon maintien du système osseux',
        'warning': 'La vitamine D joue un rôle essentiel dans la fixation du calcium au niveau des os, mais les apports sont difficiles à atteindre dans le cadre alimentaire. De plus, le corps sait en fabriquer lui-même par l\'exposition de la peau aux rayons du soleil. 90% des français sont carencés en vitamine D. Parlez-en à votre médecin, qui pourra vous prescrire une éventuelle supplémentation.',
        'indicators': [
            'calcium',
            'phosphore',
            'cuivre',
            'vitaminec'
        ]},
    'skin':
        {'title': 'Pack "Santé de la peau, cheveux et ongles"',
        'description': 'Vitamines et minéraux ayant un impact fort sur les mécanismes cutanés',
        'key': 'skin',
        'indicators': [
            "vitaminea",
            'vitamineb3',
            'vitamineb5',
            'vitamineb6',
            "vitamineb12",
            "vitaminec",
            "vitaminee",
            'zinc',
            'selenium',
            'magnesium',
            'fer'
        ]},
    'heart':
        {'title': 'Pack "Santé du cour et des artères"',
        'description': 'Contrôle de la qualité des graisses et des vitamines essentielles au bon fonctionnement du coeur / du système artériel',
        'key': 'heart',
        'indicators': [
            "agmonoinsatures",
            "acidesgrassatures",
            "acidesgrasnocifs",
            "vitamineb9",
            "vitamineb12",
            "vitaminee",
        ]},
}


def update_nutrient_packs(apps, schema_editor):

    NutrientPack = apps.get_model('nutrient', 'NutrientPack')
    Nutrient     = apps.get_model('nutrient', 'Nutrient')


    pack_by_key = dict((np.key, np) for np in NutrientPack.objects.all())

    for key, data in INDICATOR_PACKS.items():

        pack = pack_by_key[key]

        pack.title = data['title']
        pack.description = data['description']
        pack.warning = data.get('warning', '')
        pack.save()

        pack.nutrients.clear()

        nutrients = Nutrient.objects.filter(key__in=data['indicators'])

        pack.nutrients.add(*nutrients)



class Migration(migrations.Migration):

    dependencies = [
        ('nutrient', '0005_auto_20180116_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrientpack',
            name='warning',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(update_nutrient_packs)
    ]
