# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 15:23
from __future__ import unicode_literals

from django.db import migrations

def moveh3toh2(apps, schema_editor):
    Article    = apps.get_model("articles", "Article")

    for article in Article.objects.all():
        article.content = article.content.replace("<h3>", "<h2>").replace("</h3>", "</h2>")
        article.content = article.content.replace("<h4>", "<h3>").replace("</h4>", "</h3>")
        article.save()

class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_created_by'),
    ]

    operations = [
        migrations.RunPython(moveh3toh2)
    ]
