# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160624_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
    ]
