# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-14 16:47
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone
import datetime


def update_metaplannings(apps, schema_editor):

    Dish = apps.get_model("planning_mgr", "Dish")

    yesterday = timezone.now() - datetime.timedelta(days=1)
    metaplanning_old = datetime.datetime(2010, 1, 1)

    Dish.objects.all().update(activated=False)
    Dish.objects.filter(Q(meal_slot__day__date__gte=yesterday) | Q(meal_slot__day__date__lte=metaplanning_old),
                        dish_type__name__in=["Plat principal", "Plat complet", "Accompagnement"],
                        ).update(activated=True)

class Migration(migrations.Migration):

    dependencies = [
        ('planning_mgr', '0006_remove_mealtype_default_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='activated',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(update_metaplannings)
    ]
