# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-14 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_mgr', '0007_dish_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishrecipe',
            name='in_shopping_list',
            field=models.BooleanField(default=True),
        ),
    ]
