# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 09:38
from __future__ import unicode_literals

from django.db import migrations


def lunchpack_to_home(apps, schema_editor):
    MealPlace = apps.get_model('planning_mgr', 'MealPlace')

    lunchpack = MealPlace.objects.get(key="lunchpack")
    home = MealPlace.objects.get(key="home")

    MealSlot = apps.get_model('planning_mgr', 'MealSlot')

    MealSlot.objects.filter(meal_place=lunchpack).update(meal_place=home)


class Migration(migrations.Migration):

    dependencies = [
        ('planning_mgr', '0008_dishrecipe_in_shopping_list'),
    ]

    operations = [
        # migrations.RunPython(lunchpack_to_home)
    ]
