# Generated by Django 2.0.2 on 2018-02-05 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning_mgr', '0009_auto_20171220_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishrecipe',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mealdishoption',
            name='default_recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_mgr.Recipe'),
        ),
    ]
