# Generated by Django 4.2.7 on 2024-01-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_mgr', '0010_auto_20180205_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='skipped',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
