# Generated by Django 2.0.2 on 2018-02-05 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_auto_20150609_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='dietician',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_discussions', to=settings.AUTH_USER_MODEL),
        ),
    ]
